apiVersion: v1
kind: Pod
metadata:
  labels:
    app: node-exporter
  name: node-exporter
spec:
  containers:
    image: quay.io/prometheus/node-exporter:v1.7.0
    name: node-exporter-container
    ports:
    - containerPort: 9100
      hostPort: 9100
    securityContext: {}
    tty: true

