apiVersion: v1
kind: Pod
metadata:
  labels:
    app: promtail
  name: promtail
spec:
  containers:
  - args:
    - -config.file=/etc/promtail/config.yml
    image: docker.io/grafana/promtail:2.8.11
    name: promtail-container
    tty: true
    volumeMounts:
    - mountPath: /etc/promtail
      name: promtail-config-pvc
    - mountPath: /var/log
      name: promtail-log-pvc
  volumes:
  - name: promtail-config-pvc
    persistentVolumeClaim:
      claimName: promtail-config
  - name: promtail-log-pvc
    persistentVolumeClaim:
      claimName: promtail-log

