apiVersion: v1
kind: Pod
metadata:
  labels:
    app: blackbox-exporter
  name: blackbox-exporter
spec:
  containers:
  - args:
    - --config.file=/etc/blackbox_exporter/config.yml
    image: quay.io/prometheus/blackbox-exporter:v0.24.0
    name: blackbox-exporter-container
    ports:
    - containerPort: 9115
      hostPort: 9115
    tty: true
    volumeMounts:
    - mountPath: /config
      name: blackbox-config-pvc
  volumes:
  - name: blackbox-config-pvc
    persistentVolumeClaim:
      claimName: blackbox-config

